package com.miniagent.prompt;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * PromptFactory encapsulates the abstract framing and prompt engineering mechanics
 * for the generic Worker-Evaluator-Prompter loops.
 * <p>
 * This class abstracts away structural string concatenations, allowing the agent
 * layer to just feed Lists and Maps of context without worrying about spacing,
 * bullets, or JSON-string escaping.
 */
public class PromptFactory {

    /**
     * Builds the system instructions for a highly obedient generator worker.
     * 
     * @param domainContext Specific domain constraints (e.g., "You are a medical scribe").
     * @return The formatted System prompt.
     */
    public String buildWorkerSystemPrompt(String domainContext) {
        return joinLines(
                "You are an autonomous worker agent strictly adhering to the user's constraints.",
                domainContext != null ? domainContext : "",
                "Return your output as a valid JSON object with the exact keys instructed.",
                "Always populate 'thought_process' first to plan your response.",
                "Ensure your main output resides only in the 'summary' key.",
                "Ensure any meta-commentary, clarifying questions, or conversation resides only in the 'convo' key.",
                "Under no circumstances should meta-commentary, apology, or 'missing data' language pollute the main output."
        );
    }

    /**
     * Builds the user prompt for the generative worker.
     * 
     * @param taskInstructions The immediate task at hand.
     * @param dataset A map of facts or variables needed to complete the task.
     * @param liveInjections Instructions dynamically added mid-way that MUST be addressed.
     * @return The formatted User prompt.
     */
    public String buildWorkerUserPrompt(String taskInstructions, Map<String, Object> dataset, List<String> liveInjections) {
        return joinSections(
                "TASK", taskInstructions,
                "LIVE INJECTIONS (MUST FOLLOW)", bullets(liveInjections),
                "DATASET", mapToText(dataset)
        );
    }

    /**
     * Builds the system prompt for the multi-dimensional evaluator.
     * <p>
     * Instead of a one-dimensional pass/fail, the evaluator uses strict scoring logic
     * mapped across four dimensions.
     * 
     * @return The formatted Evaluator System prompt.
     */
    public String buildEvaluatorSystemPrompt() {
        return joinLines(
                "You are an elite, merciless Evaluator AI.",
                "Your job is to analyze the Worker's draft output against the provided instructions and Dataset.",
                "Output MUST be in the following plain-text block format:",
                "FACTUALITY_SCORE: (0-100)",
                "STRUCTURE_SCORE: (0-100)",
                "STYLE_SCORE: (0-100)",
                "INSTRUCTION_ADHERENCE_SCORE: (0-100)",
                "PASS: (true/false)",
                "FACTUALITY_FIXES:",
                "- (list)",
                "STRUCTURE_FIXES:",
                "- (list)",
                "STYLE_FIXES:",
                "- (list)",
                "MISSING_INSTRUCTIONS:",
                "- (list instructions ignored by worker)",
                "RATIONALE:",
                "(short paragraph reasoning)"
        );
    }

    /**
     * Builds the user prompt for the Evaluator, supplying the worker's draft and the 
     * original context to score against.
     * 
     * @param draft The unverified output generated by the worker.
     * @param rules The rigid rules the worker was supposed to follow.
     * @param dataset The original data.
     * @param liveInjections Mid-way instructions. If missing from the draft, score drops drastically.
     * @return The formatted Evaluator user prompt.
     */
    public String buildEvaluatorUserPrompt(String draft, List<String> rules, Map<String, Object> dataset, List<String> liveInjections) {
        return joinSections(
                "WORKER DRAFT OUTPUT", draft,
                "RIGID RULES & STRUCTURE", bullets(rules),
                "LIVE INJECTIONS REQUIRED", bullets(liveInjections),
                "ORIGINAL DATASET", mapToText(dataset),
                "EVALUATION CRITERIA", joinLines(
                        "1. Identify pure hallucinations or facts unsupported by the DATASET (Factuality).",
                        "2. Ensure all RIGID RULES are followed verbatim (Structure).",
                        "3. Ensure the tone is appropriate (Style).",
                        "4. CRITICAL: If ANY item in LIVE INJECTIONS is ignored, the INSTRUCTION_ADHERENCE_SCORE must be below 50, and you must explicitly list it in MISSING_INSTRUCTIONS."
                )
        );
    }

    /**
     * Builds the system prompt for the repair cycle. It mandates that critics' warnings
     * are functionally resolved, not just acknowledged.
     * 
     * @return The formatted Repair System prompt.
     */
    public String buildRepairSystemPrompt() {
        return joinLines(
                "You are fixing a broken draft that failed an elite Critic Evaluation.",
                "Your objective is to ingest the exact FIXES provided by the Critic and integrate them.",
                "Return a JSON object with 'thought_process', 'summary', and 'convo'.",
                "Explain how you resolved the Critic's issues step-by-step in 'thought_process'."
        );
    }

    /**
     * Builds the highly specific error-correcting user prompt for the repair cycle.
     * 
     * @param previousDraft The broken draft.
     * @param factualityFixes Factuality errors flagged.
     * @param structuralFixes Formatting errors flagged.
     * @param missingInstructions Dropped live-injections.
     * @param dataset The original facts.
     * @return The formatted Repair user prompt.
     */
    public String buildRepairUserPrompt(
            String previousDraft,
            List<String> factualityFixes,
            List<String> structuralFixes,
            List<String> missingInstructions,
            Map<String, Object> dataset
    ) {
        return joinSections(
                "BROKEN DRAFT", previousDraft,
                "FACTUALITY FIXES REQUIRED", bullets(factualityFixes),
                "STRUCTURAL FIXES REQUIRED", bullets(structuralFixes),
                "IGNORED INSTRUCTIONS REQUIRED", bullets(missingInstructions),
                "ORIGINAL DATASET", mapToText(dataset),
                "DIRECTIVE", "Do not ignore the fixes. Apply them literally."
        );
    }


    /* --- HELPER METHODS --- */

    /**
     * Bullet formatter used across prompt sections. Converts flat lists into markdown dashes.
     */
    private String bullets(List<String> items) {
        if (items == null || items.isEmpty()) {
            return "- none";
        }
        return items.stream()
                .filter(item -> item != null && !item.isBlank())
                .map(String::trim)
                .map(item -> item.startsWith("-") ? item : "- " + item)
                .collect(Collectors.joining("\n"));
    }

    /**
     * Renders a nested dataset map into highly readable structured prompt text.
     */
    private String mapToText(Map<String, Object> map) {
        if (map == null || map.isEmpty()) {
            return "{}";
        }
        return map.entrySet().stream()
                .map(entry -> entry.getKey() + "=" + String.valueOf(entry.getValue()))
                .collect(Collectors.joining("\n"));
    }

    /**
     * Joins multiple titled sections with stable, standardized line-break spacing.
     */
    private String joinSections(String... pieces) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i + 1 < pieces.length; i += 2) {
            String title = pieces[i];
            String body = pieces[i + 1] == null ? "" : pieces[i + 1];
            if (sb.length() > 0) {
                sb.append("\n\n");
            }
            sb.append(title).append("\n").append(body);
        }
        return sb.toString();
    }

    /**
     * Joins lines with unified newline separators.
     */
    private String joinLines(String... lines) {
        return String.join("\n", lines);
    }
}
